//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 09:10:02 AM IST 
//

package tech.ecoa.osets.model.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the tech.ecoa.osets.model.types package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Library_QNAME = new QName("http://www.ecoa.technology/types-1.0", "library");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: tech.ecoa.osets.model.types
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Library }
	 * 
	 */
	public Library createLibrary() {
		return new Library();
	}

	/**
	 * Create an instance of {@link Use }
	 * 
	 */
	public Use createUse() {
		return new Use();
	}

	/**
	 * Create an instance of {@link Enum }
	 * 
	 */
	public Enum createEnum() {
		return new Enum();
	}

	/**
	 * Create an instance of {@link Constant }
	 * 
	 */
	public Constant createConstant() {
		return new Constant();
	}

	/**
	 * Create an instance of {@link EnumValue }
	 * 
	 */
	public EnumValue createEnumValue() {
		return new EnumValue();
	}

	/**
	 * Create an instance of {@link Union }
	 * 
	 */
	public Union createUnion() {
		return new Union();
	}

	/**
	 * Create an instance of {@link Simple }
	 * 
	 */
	public Simple createSimple() {
		return new Simple();
	}

	/**
	 * Create an instance of {@link Field }
	 * 
	 */
	public Field createField() {
		return new Field();
	}

	/**
	 * Create an instance of {@link FixedArray }
	 * 
	 */
	public FixedArray createFixedArray() {
		return new FixedArray();
	}

	/**
	 * Create an instance of {@link Record }
	 * 
	 */
	public Record createRecord() {
		return new Record();
	}

	/**
	 * Create an instance of {@link VariantRecord }
	 * 
	 */
	public VariantRecord createVariantRecord() {
		return new VariantRecord();
	}

	/**
	 * Create an instance of {@link Array }
	 * 
	 */
	public Array createArray() {
		return new Array();
	}

	/**
	 * Create an instance of {@link DataTypes }
	 * 
	 */
	public DataTypes createDataTypes() {
		return new DataTypes();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Library
	 * }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.ecoa.technology/types-1.0", name = "library")
	public JAXBElement<Library> createLibrary(Library value) {
		return new JAXBElement<Library>(_Library_QNAME, Library.class, null, value);
	}

}
