//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 09:10:02 AM IST 
//

package tech.ecoa.osets.model.types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A record with variable parts: each "union" exists only if the selector has
 * the value given by the "when" attribute.
 * 
 * 
 * <p>
 * Java class for VariantRecord complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="VariantRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field" type="{http://www.ecoa.technology/types-1.0}Field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="union" type="{http://www.ecoa.technology/types-1.0}Union" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.ecoa.technology/types-1.0}TypeName" />
 *       &lt;attribute name="selectName" use="required" type="{http://www.ecoa.technology/types-1.0}NameId" />
 *       &lt;attribute name="selectType" use="required" type="{http://www.ecoa.technology/types-1.0}TypeQName" />
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VariantRecord", propOrder = { "field", "union" })
public class VariantRecord {

	protected List<Field> field;
	@XmlElement(required = true)
	protected List<Union> union;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "selectName", required = true)
	protected String selectName;
	@XmlAttribute(name = "selectType", required = true)
	protected String selectType;
	@XmlAttribute(name = "comment")
	protected String comment;

	/**
	 * Gets the value of the field property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the field property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getField().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Field }
	 * 
	 * 
	 */
	public List<Field> getField() {
		if (field == null) {
			field = new ArrayList<Field>();
		}
		return this.field;
	}

	/**
	 * Gets the value of the union property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the union property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getUnion().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Union }
	 * 
	 * 
	 */
	public List<Union> getUnion() {
		if (union == null) {
			union = new ArrayList<Union>();
		}
		return this.union;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the selectName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSelectName() {
		return selectName;
	}

	/**
	 * Sets the value of the selectName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSelectName(String value) {
		this.selectName = value;
	}

	/**
	 * Gets the value of the selectType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSelectType() {
		return selectType;
	}

	/**
	 * Sets the value of the selectType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSelectType(String value) {
		this.selectType = value;
	}

	/**
	 * Gets the value of the comment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * Sets the value of the comment property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComment(String value) {
		this.comment = value;
	}

}
