//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:12 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step5cDeployment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Defines level of logging for a deployed module instance
 * 
 * 
 * <p>
 * Java class for ModuleLog complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleLog">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="instanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enabledLevels" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleLog")
public class ModuleLog {

	@XmlAttribute(name = "instanceName", required = true)
	protected String instanceName;
	@XmlAttribute(name = "enabledLevels", required = true)
	protected String enabledLevels;

	/**
	 * Gets the value of the instanceName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInstanceName() {
		return instanceName;
	}

	/**
	 * Sets the value of the instanceName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInstanceName(String value) {
		this.instanceName = value;
	}

	/**
	 * Gets the value of the enabledLevels property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnabledLevels() {
		return enabledLevels;
	}

	/**
	 * Sets the value of the enabledLevels property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEnabledLevels(String value) {
		this.enabledLevels = value;
	}

}
