//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.10 at 03:49:20 PM IST 
//

package tech.ecoa.osets.model.deploy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Defines default level of logging for a given component
 * 
 * 
 * <p>
 * Java class for ComponentLog complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentLog">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="moduleLog" type="{http://www.ecoa.technology/deployment-1.0}ModuleLog" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="instanceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enabledLevels" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentLog", propOrder = { "moduleLog" })
public class ComponentLog {

	protected List<ModuleLog> moduleLog;
	@XmlAttribute(name = "instanceName", required = true)
	protected String instanceName;
	@XmlAttribute(name = "enabledLevels", required = true)
	protected String enabledLevels;

	/**
	 * Gets the value of the moduleLog property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the moduleLog property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getModuleLog().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link ModuleLog
	 * }
	 * 
	 * 
	 */
	public List<ModuleLog> getModuleLog() {
		if (moduleLog == null) {
			moduleLog = new ArrayList<ModuleLog>();
		}
		return this.moduleLog;
	}

	/**
	 * Gets the value of the instanceName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInstanceName() {
		return instanceName;
	}

	/**
	 * Sets the value of the instanceName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInstanceName(String value) {
		this.instanceName = value;
	}

	/**
	 * Gets the value of the enabledLevels property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnabledLevels() {
		return enabledLevels;
	}

	/**
	 * Sets the value of the enabledLevels property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEnabledLevels(String value) {
		this.enabledLevels = value;
	}

}
