//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.10 at 03:49:20 PM IST 
//

package tech.ecoa.osets.model.deploy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Deployment complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Deployment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="protectionDomain" type="{http://www.ecoa.technology/deployment-1.0}ProtectionDomain" maxOccurs="unbounded"/>
 *         &lt;element name="logPolicy" type="{http://www.ecoa.technology/deployment-1.0}LogPolicy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="platformConfiguration" type="{http://www.ecoa.technology/deployment-1.0}PlatformConfiguration" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="finalAssembly" use="required" type="{http://www.ecoa.technology/deployment-1.0}NameId" />
 *       &lt;attribute name="logicalSystem" use="required" type="{http://www.ecoa.technology/deployment-1.0}NameId" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deployment", propOrder = { "protectionDomain", "logPolicy", "platformConfiguration" })
public class Deployment {

	@XmlElement(required = true)
	protected List<ProtectionDomain> protectionDomain;
	protected List<LogPolicy> logPolicy;
	@XmlElement(required = true)
	protected List<PlatformConfiguration> platformConfiguration;
	@XmlAttribute(name = "finalAssembly", required = true)
	protected String finalAssembly;
	@XmlAttribute(name = "logicalSystem", required = true)
	protected String logicalSystem;

	/**
	 * Gets the value of the protectionDomain property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the protectionDomain property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getProtectionDomain().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ProtectionDomain }
	 * 
	 * 
	 */
	public List<ProtectionDomain> getProtectionDomain() {
		if (protectionDomain == null) {
			protectionDomain = new ArrayList<ProtectionDomain>();
		}
		return this.protectionDomain;
	}

	/**
	 * Gets the value of the logPolicy property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the logPolicy property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLogPolicy().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link LogPolicy
	 * }
	 * 
	 * 
	 */
	public List<LogPolicy> getLogPolicy() {
		if (logPolicy == null) {
			logPolicy = new ArrayList<LogPolicy>();
		}
		return this.logPolicy;
	}

	/**
	 * Gets the value of the platformConfiguration property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the platformConfiguration property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPlatformConfiguration().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PlatformConfiguration }
	 * 
	 * 
	 */
	public List<PlatformConfiguration> getPlatformConfiguration() {
		if (platformConfiguration == null) {
			platformConfiguration = new ArrayList<PlatformConfiguration>();
		}
		return this.platformConfiguration;
	}

	/**
	 * Gets the value of the finalAssembly property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFinalAssembly() {
		return finalAssembly;
	}

	/**
	 * Sets the value of the finalAssembly property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFinalAssembly(String value) {
		this.finalAssembly = value;
	}

	/**
	 * Gets the value of the logicalSystem property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLogicalSystem() {
		return logicalSystem;
	}

	/**
	 * Sets the value of the logicalSystem property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLogicalSystem(String value) {
		this.logicalSystem = value;
	}

}
