//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 07:36:06 AM IST 
//

package tech.ecoa.osets.model.cimp;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DynamicTriggerInstance complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DynamicTriggerInstance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ecoa.technology/implementation-1.0}Instance">
 *       &lt;sequence>
 *         &lt;element name="parameter" type="{http://www.ecoa.technology/implementation-1.0}Parameter" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1" />
 *       &lt;attribute name="delayMin" type="{http://www.ecoa.technology/implementation-1.0}TimeDuration" default="0.0" />
 *       &lt;attribute name="delayMax" type="{http://www.ecoa.technology/implementation-1.0}TimeDuration" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DynamicTriggerInstance", propOrder = { "parameter" })
public class DynamicTriggerInstance extends Instance {

	protected List<Parameter> parameter;
	@XmlAttribute(name = "size")
	@XmlSchemaType(name = "positiveInteger")
	protected BigInteger size;
	@XmlAttribute(name = "delayMin")
	protected Double delayMin;
	@XmlAttribute(name = "delayMax")
	protected Double delayMax;

	/**
	 * Gets the value of the parameter property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the parameter property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getParameter().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Parameter
	 * }
	 * 
	 * 
	 */
	public List<Parameter> getParameter() {
		if (parameter == null) {
			parameter = new ArrayList<Parameter>();
		}
		return this.parameter;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSize() {
		if (size == null) {
			return new BigInteger("1");
		} else {
			return size;
		}
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSize(BigInteger value) {
		this.size = value;
	}

	/**
	 * Gets the value of the delayMin property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public double getDelayMin() {
		if (delayMin == null) {
			return 0.0D;
		} else {
			return delayMin;
		}
	}

	/**
	 * Sets the value of the delayMin property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setDelayMin(Double value) {
		this.delayMin = value;
	}

	/**
	 * Gets the value of the delayMax property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getDelayMax() {
		return delayMax;
	}

	/**
	 * Sets the value of the delayMax property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setDelayMax(Double value) {
		this.delayMax = value;
	}

}
