//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 07:36:06 AM IST 
//

package tech.ecoa.osets.model.cimp;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Describes a single-threaded ECOA module, implemented as software,
 * contributing to the implementation of an ECOA component.
 * 
 * 
 * <p>
 * Java class for ModuleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="properties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="property" type="{http://www.ecoa.technology/implementation-1.0}Parameter" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pinfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="publicPinfo" type="{http://www.ecoa.technology/implementation-1.0}PublicPinfo" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="privatePinfo" type="{http://www.ecoa.technology/implementation-1.0}PrivatePinfo" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="operations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="dataWritten" type="{http://www.ecoa.technology/implementation-1.0}VersionedData" minOccurs="0"/>
 *                   &lt;element name="dataRead" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.ecoa.technology/implementation-1.0}VersionedData">
 *                           &lt;attribute name="notifying" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="eventSent" type="{http://www.ecoa.technology/implementation-1.0}Event" minOccurs="0"/>
 *                   &lt;element name="eventReceived" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.ecoa.technology/implementation-1.0}Event">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="requestSent" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.ecoa.technology/implementation-1.0}RequestResponse">
 *                           &lt;attribute name="timeout" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="isSynchronous" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="maxConcurrentRequests" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="requestReceived" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.ecoa.technology/implementation-1.0}RequestResponse">
 *                           &lt;attribute name="maxConcurrentRequests" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.ecoa.technology/implementation-1.0}NameId" />
 *       &lt;attribute name="isSupervisionModule" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isFaultHandler" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="activatingSvcAvailNotifs" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="enableModuleLifeCycleNotifs" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="activatingErrorNotifs" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleType", propOrder = { "properties", "pinfo", "operations" })
public class ModuleType {

	protected ModuleType.Properties properties;
	protected ModuleType.Pinfo pinfo;
	@XmlElement(required = true)
	protected ModuleType.Operations operations;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "isSupervisionModule")
	protected Boolean isSupervisionModule;
	@XmlAttribute(name = "isFaultHandler")
	protected Boolean isFaultHandler;
	@XmlAttribute(name = "activatingSvcAvailNotifs")
	protected Boolean activatingSvcAvailNotifs;
	@XmlAttribute(name = "enableModuleLifeCycleNotifs")
	protected Boolean enableModuleLifeCycleNotifs;
	@XmlAttribute(name = "activatingErrorNotifs")
	protected Boolean activatingErrorNotifs;

	/**
	 * Gets the value of the properties property.
	 * 
	 * @return possible object is {@link ModuleType.Properties }
	 * 
	 */
	public ModuleType.Properties getProperties() {
		return properties;
	}

	/**
	 * Sets the value of the properties property.
	 * 
	 * @param value
	 *            allowed object is {@link ModuleType.Properties }
	 * 
	 */
	public void setProperties(ModuleType.Properties value) {
		this.properties = value;
	}

	/**
	 * Gets the value of the pinfo property.
	 * 
	 * @return possible object is {@link ModuleType.Pinfo }
	 * 
	 */
	public ModuleType.Pinfo getPinfo() {
		return pinfo;
	}

	/**
	 * Sets the value of the pinfo property.
	 * 
	 * @param value
	 *            allowed object is {@link ModuleType.Pinfo }
	 * 
	 */
	public void setPinfo(ModuleType.Pinfo value) {
		this.pinfo = value;
	}

	/**
	 * Gets the value of the operations property.
	 * 
	 * @return possible object is {@link ModuleType.Operations }
	 * 
	 */
	public ModuleType.Operations getOperations() {
		return operations;
	}

	/**
	 * Sets the value of the operations property.
	 * 
	 * @param value
	 *            allowed object is {@link ModuleType.Operations }
	 * 
	 */
	public void setOperations(ModuleType.Operations value) {
		this.operations = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the isSupervisionModule property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isIsSupervisionModule() {
		if (isSupervisionModule == null) {
			return false;
		} else {
			return isSupervisionModule;
		}
	}

	/**
	 * Sets the value of the isSupervisionModule property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsSupervisionModule(Boolean value) {
		this.isSupervisionModule = value;
	}

	/**
	 * Gets the value of the isFaultHandler property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isIsFaultHandler() {
		if (isFaultHandler == null) {
			return false;
		} else {
			return isFaultHandler;
		}
	}

	/**
	 * Sets the value of the isFaultHandler property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsFaultHandler(Boolean value) {
		this.isFaultHandler = value;
	}

	/**
	 * Gets the value of the activatingSvcAvailNotifs property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isActivatingSvcAvailNotifs() {
		if (activatingSvcAvailNotifs == null) {
			return true;
		} else {
			return activatingSvcAvailNotifs;
		}
	}

	/**
	 * Sets the value of the activatingSvcAvailNotifs property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setActivatingSvcAvailNotifs(Boolean value) {
		this.activatingSvcAvailNotifs = value;
	}

	/**
	 * Gets the value of the enableModuleLifeCycleNotifs property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isEnableModuleLifeCycleNotifs() {
		if (enableModuleLifeCycleNotifs == null) {
			return true;
		} else {
			return enableModuleLifeCycleNotifs;
		}
	}

	/**
	 * Sets the value of the enableModuleLifeCycleNotifs property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setEnableModuleLifeCycleNotifs(Boolean value) {
		this.enableModuleLifeCycleNotifs = value;
	}

	/**
	 * Gets the value of the activatingErrorNotifs property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isActivatingErrorNotifs() {
		if (activatingErrorNotifs == null) {
			return true;
		} else {
			return activatingErrorNotifs;
		}
	}

	/**
	 * Sets the value of the activatingErrorNotifs property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setActivatingErrorNotifs(Boolean value) {
		this.activatingErrorNotifs = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;choice maxOccurs="unbounded">
	 *         &lt;element name="dataWritten" type="{http://www.ecoa.technology/implementation-1.0}VersionedData" minOccurs="0"/>
	 *         &lt;element name="dataRead" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;extension base="{http://www.ecoa.technology/implementation-1.0}VersionedData">
	 *                 &lt;attribute name="notifying" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *               &lt;/extension>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="eventSent" type="{http://www.ecoa.technology/implementation-1.0}Event" minOccurs="0"/>
	 *         &lt;element name="eventReceived" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;extension base="{http://www.ecoa.technology/implementation-1.0}Event">
	 *               &lt;/extension>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="requestSent" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;extension base="{http://www.ecoa.technology/implementation-1.0}RequestResponse">
	 *                 &lt;attribute name="timeout" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
	 *                 &lt;attribute name="isSynchronous" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *                 &lt;attribute name="maxConcurrentRequests" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
	 *               &lt;/extension>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="requestReceived" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;extension base="{http://www.ecoa.technology/implementation-1.0}RequestResponse">
	 *                 &lt;attribute name="maxConcurrentRequests" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
	 *               &lt;/extension>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/choice>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "dataWrittenOrDataReadOrEventSent" })
	public static class Operations {

		@XmlElements({ @XmlElement(name = "dataWritten", type = VersionedData.class), @XmlElement(name = "dataRead", type = ModuleType.Operations.DataRead.class), @XmlElement(name = "eventSent", type = Event.class), @XmlElement(name = "eventReceived", type = ModuleType.Operations.EventReceived.class), @XmlElement(name = "requestSent", type = ModuleType.Operations.RequestSent.class), @XmlElement(name = "requestReceived", type = ModuleType.Operations.RequestReceived.class) })
		protected List<Object> dataWrittenOrDataReadOrEventSent;

		/**
		 * Gets the value of the dataWrittenOrDataReadOrEventSent property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the dataWrittenOrDataReadOrEventSent
		 * property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDataWrittenOrDataReadOrEventSent().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link VersionedData } {@link ModuleType.Operations.DataRead }
		 * {@link Event } {@link ModuleType.Operations.EventReceived }
		 * {@link ModuleType.Operations.RequestSent }
		 * {@link ModuleType.Operations.RequestReceived }
		 * 
		 * 
		 */
		public List<Object> getDataWrittenOrDataReadOrEventSent() {
			if (dataWrittenOrDataReadOrEventSent == null) {
				dataWrittenOrDataReadOrEventSent = new ArrayList<Object>();
			}
			return this.dataWrittenOrDataReadOrEventSent;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;extension base="{http://www.ecoa.technology/implementation-1.0}VersionedData">
		 *       &lt;attribute name="notifying" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
		 *     &lt;/extension>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class DataRead extends VersionedData {

			@XmlAttribute(name = "notifying")
			protected Boolean notifying;

			/**
			 * Gets the value of the notifying property.
			 * 
			 * @return possible object is {@link Boolean }
			 * 
			 */
			public boolean isNotifying() {
				if (notifying == null) {
					return false;
				} else {
					return notifying;
				}
			}

			/**
			 * Sets the value of the notifying property.
			 * 
			 * @param value
			 *            allowed object is {@link Boolean }
			 * 
			 */
			public void setNotifying(Boolean value) {
				this.notifying = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;extension base="{http://www.ecoa.technology/implementation-1.0}Event">
		 *     &lt;/extension>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class EventReceived extends Event {

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;extension base="{http://www.ecoa.technology/implementation-1.0}RequestResponse">
		 *       &lt;attribute name="maxConcurrentRequests" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
		 *     &lt;/extension>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class RequestReceived extends RequestResponse {

			@XmlAttribute(name = "maxConcurrentRequests")
			@XmlSchemaType(name = "positiveInteger")
			protected BigInteger maxConcurrentRequests;

			/**
			 * Gets the value of the maxConcurrentRequests property.
			 * 
			 * @return possible object is {@link BigInteger }
			 * 
			 */
			public BigInteger getMaxConcurrentRequests() {
				if (maxConcurrentRequests == null) {
					return new BigInteger("10");
				} else {
					return maxConcurrentRequests;
				}
			}

			/**
			 * Sets the value of the maxConcurrentRequests property.
			 * 
			 * @param value
			 *            allowed object is {@link BigInteger }
			 * 
			 */
			public void setMaxConcurrentRequests(BigInteger value) {
				this.maxConcurrentRequests = value;
			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;extension base="{http://www.ecoa.technology/implementation-1.0}RequestResponse">
		 *       &lt;attribute name="timeout" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
		 *       &lt;attribute name="isSynchronous" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
		 *       &lt;attribute name="maxConcurrentRequests" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
		 *     &lt;/extension>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class RequestSent extends RequestResponse {

			@XmlAttribute(name = "timeout", required = true)
			protected double timeout;
			@XmlAttribute(name = "isSynchronous", required = true)
			protected boolean isSynchronous;
			@XmlAttribute(name = "maxConcurrentRequests")
			@XmlSchemaType(name = "positiveInteger")
			protected BigInteger maxConcurrentRequests;

			/**
			 * Gets the value of the timeout property.
			 * 
			 */
			public double getTimeout() {
				return timeout;
			}

			/**
			 * Sets the value of the timeout property.
			 * 
			 */
			public void setTimeout(double value) {
				this.timeout = value;
			}

			/**
			 * Gets the value of the isSynchronous property.
			 * 
			 */
			public boolean isIsSynchronous() {
				return isSynchronous;
			}

			/**
			 * Sets the value of the isSynchronous property.
			 * 
			 */
			public void setIsSynchronous(boolean value) {
				this.isSynchronous = value;
			}

			/**
			 * Gets the value of the maxConcurrentRequests property.
			 * 
			 * @return possible object is {@link BigInteger }
			 * 
			 */
			public BigInteger getMaxConcurrentRequests() {
				if (maxConcurrentRequests == null) {
					return new BigInteger("10");
				} else {
					return maxConcurrentRequests;
				}
			}

			/**
			 * Sets the value of the maxConcurrentRequests property.
			 * 
			 * @param value
			 *            allowed object is {@link BigInteger }
			 * 
			 */
			public void setMaxConcurrentRequests(BigInteger value) {
				this.maxConcurrentRequests = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="publicPinfo" type="{http://www.ecoa.technology/implementation-1.0}PublicPinfo" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="privatePinfo" type="{http://www.ecoa.technology/implementation-1.0}PrivatePinfo" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "publicPinfo", "privatePinfo" })
	public static class Pinfo {

		protected List<PublicPinfo> publicPinfo;
		protected List<PrivatePinfo> privatePinfo;

		/**
		 * Gets the value of the publicPinfo property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the publicPinfo property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPublicPinfo().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link PublicPinfo }
		 * 
		 * 
		 */
		public List<PublicPinfo> getPublicPinfo() {
			if (publicPinfo == null) {
				publicPinfo = new ArrayList<PublicPinfo>();
			}
			return this.publicPinfo;
		}

		/**
		 * Gets the value of the privatePinfo property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the privatePinfo property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPrivatePinfo().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link PrivatePinfo }
		 * 
		 * 
		 */
		public List<PrivatePinfo> getPrivatePinfo() {
			if (privatePinfo == null) {
				privatePinfo = new ArrayList<PrivatePinfo>();
			}
			return this.privatePinfo;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="property" type="{http://www.ecoa.technology/implementation-1.0}Parameter" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "property" })
	public static class Properties {

		@XmlElement(required = true)
		protected List<Parameter> property;

		/**
		 * Gets the value of the property property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the property property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getProperty().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Parameter }
		 * 
		 * 
		 */
		public List<Parameter> getProperty() {
			if (property == null) {
				property = new ArrayList<Parameter>();
			}
			return this.property;
		}

	}

}
