//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 07:36:06 AM IST 
//

package tech.ecoa.osets.model.cimp;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Describes an instance of a Module (having its own internal state).
 * 
 * 
 * <p>
 * Java class for ModuleInstance complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ModuleInstance">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ecoa.technology/implementation-1.0}Instance">
 *       &lt;sequence>
 *         &lt;element name="propertyValues" type="{http://www.ecoa.technology/implementation-1.0}PropertyValues" minOccurs="0"/>
 *         &lt;element name="pinfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="publicPinfo" type="{http://www.ecoa.technology/implementation-1.0}PinfoValue" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="privatePinfo" type="{http://www.ecoa.technology/implementation-1.0}PinfoValue" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="implementationName" use="required" type="{http://www.ecoa.technology/implementation-1.0}NameId" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModuleInstance", propOrder = { "propertyValues", "pinfo" })
public class ModuleInstance extends Instance {

	protected PropertyValues propertyValues;
	protected ModuleInstance.Pinfo pinfo;
	@XmlAttribute(name = "implementationName", required = true)
	protected String implementationName;

	/**
	 * Gets the value of the propertyValues property.
	 * 
	 * @return possible object is {@link PropertyValues }
	 * 
	 */
	public PropertyValues getPropertyValues() {
		return propertyValues;
	}

	/**
	 * Sets the value of the propertyValues property.
	 * 
	 * @param value
	 *            allowed object is {@link PropertyValues }
	 * 
	 */
	public void setPropertyValues(PropertyValues value) {
		this.propertyValues = value;
	}

	/**
	 * Gets the value of the pinfo property.
	 * 
	 * @return possible object is {@link ModuleInstance.Pinfo }
	 * 
	 */
	public ModuleInstance.Pinfo getPinfo() {
		return pinfo;
	}

	/**
	 * Sets the value of the pinfo property.
	 * 
	 * @param value
	 *            allowed object is {@link ModuleInstance.Pinfo }
	 * 
	 */
	public void setPinfo(ModuleInstance.Pinfo value) {
		this.pinfo = value;
	}

	/**
	 * Gets the value of the implementationName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getImplementationName() {
		return implementationName;
	}

	/**
	 * Sets the value of the implementationName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setImplementationName(String value) {
		this.implementationName = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="publicPinfo" type="{http://www.ecoa.technology/implementation-1.0}PinfoValue" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="privatePinfo" type="{http://www.ecoa.technology/implementation-1.0}PinfoValue" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "publicPinfo", "privatePinfo" })
	public static class Pinfo {

		protected List<PinfoValue> publicPinfo;
		protected List<PinfoValue> privatePinfo;

		/**
		 * Gets the value of the publicPinfo property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the publicPinfo property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPublicPinfo().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link PinfoValue }
		 * 
		 * 
		 */
		public List<PinfoValue> getPublicPinfo() {
			if (publicPinfo == null) {
				publicPinfo = new ArrayList<PinfoValue>();
			}
			return this.publicPinfo;
		}

		/**
		 * Gets the value of the privatePinfo property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the privatePinfo property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPrivatePinfo().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link PinfoValue }
		 * 
		 * 
		 */
		public List<PinfoValue> getPrivatePinfo() {
			if (privatePinfo == null) {
				privatePinfo = new ArrayList<PinfoValue>();
			}
			return this.privatePinfo;
		}

	}

}
