//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:01 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step1ServiceDefs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for E_EventDirection.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="E_EventDirection">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SENT_BY_PROVIDER"/>
 *     &lt;enumeration value="RECEIVED_BY_PROVIDER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "E_EventDirection")
@XmlEnum
public enum EEventDirection {

	SENT_BY_PROVIDER, RECEIVED_BY_PROVIDER;

	public String value() {
		return name();
	}

	public static EEventDirection fromValue(String v) {
		return valueOf(v);
	}

}
