//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:08 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step4bBinDesc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * binary dependency that needs to be linked with the initial object
 * 
 * 
 * <p>
 * Java class for BinaryDependency complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BinaryDependency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="object" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="checksum" use="required" type="{http://www.ecoa.technology/bin-desc-1.0}HexOrDecValue" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinaryDependency")
public class BinaryDependency {

	@XmlAttribute(name = "object", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String object;
	@XmlAttribute(name = "checksum", required = true)
	protected String checksum;

	/**
	 * Gets the value of the object property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getObject() {
		return object;
	}

	/**
	 * Sets the value of the object property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setObject(String value) {
		this.object = value;
	}

	/**
	 * Gets the value of the checksum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChecksum() {
		return checksum;
	}

	/**
	 * Sets the value of the checksum property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChecksum(String value) {
		this.checksum = value;
	}

}
