//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:08 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step4bBinDesc;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Technical description of the binary module
 * 
 * <p>
 * Java class for BinaryModule complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BinaryModule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="binaryDependency" type="{http://www.ecoa.technology/bin-desc-1.0}BinaryDependency" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reference" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="object" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="userContextSize" use="required" type="{http://www.ecoa.technology/bin-desc-1.0}HexOrDecValue" />
 *       &lt;attribute name="warmStartContextSize" use="required" type="{http://www.ecoa.technology/bin-desc-1.0}HexOrDecValue" />
 *       &lt;attribute name="stackSize" use="required" type="{http://www.ecoa.technology/bin-desc-1.0}HexOrDecValue" />
 *       &lt;attribute name="heapSize" use="required" type="{http://www.ecoa.technology/bin-desc-1.0}HexOrDecValue" />
 *       &lt;attribute name="checksum" use="required" type="{http://www.ecoa.technology/bin-desc-1.0}HexOrDecValue" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinaryModule", propOrder = { "binaryDependencies" })
public class BinaryModule {

	@XmlElement(name = "binaryDependency")
	protected List<BinaryDependency> binaryDependencies;
	@XmlAttribute(name = "reference", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String reference;
	@XmlAttribute(name = "object", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String object;
	@XmlAttribute(name = "userContextSize", required = true)
	protected String userContextSize;
	@XmlAttribute(name = "warmStartContextSize", required = true)
	protected String warmStartContextSize;
	@XmlAttribute(name = "stackSize", required = true)
	protected String stackSize;
	@XmlAttribute(name = "heapSize", required = true)
	protected String heapSize;
	@XmlAttribute(name = "checksum", required = true)
	protected String checksum;

	/**
	 * Gets the value of the binaryDependencies property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the binaryDependencies property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBinaryDependencies().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BinaryDependency }
	 * 
	 * 
	 */
	public List<BinaryDependency> getBinaryDependencies() {
		if (binaryDependencies == null) {
			binaryDependencies = new ArrayList<BinaryDependency>();
		}
		return this.binaryDependencies;
	}

	/**
	 * Gets the value of the reference property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReference() {
		return reference;
	}

	/**
	 * Sets the value of the reference property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReference(String value) {
		this.reference = value;
	}

	/**
	 * Gets the value of the object property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getObject() {
		return object;
	}

	/**
	 * Sets the value of the object property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setObject(String value) {
		this.object = value;
	}

	/**
	 * Gets the value of the userContextSize property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUserContextSize() {
		return userContextSize;
	}

	/**
	 * Sets the value of the userContextSize property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUserContextSize(String value) {
		this.userContextSize = value;
	}

	/**
	 * Gets the value of the warmStartContextSize property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWarmStartContextSize() {
		return warmStartContextSize;
	}

	/**
	 * Sets the value of the warmStartContextSize property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWarmStartContextSize(String value) {
		this.warmStartContextSize = value;
	}

	/**
	 * Gets the value of the stackSize property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStackSize() {
		return stackSize;
	}

	/**
	 * Sets the value of the stackSize property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStackSize(String value) {
		this.stackSize = value;
	}

	/**
	 * Gets the value of the heapSize property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHeapSize() {
		return heapSize;
	}

	/**
	 * Sets the value of the heapSize property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHeapSize(String value) {
		this.heapSize = value;
	}

	/**
	 * Gets the value of the checksum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChecksum() {
		return checksum;
	}

	/**
	 * Sets the value of the checksum property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChecksum(String value) {
		this.checksum = value;
	}

}
