//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:08 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step4bBinDesc;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Links between module implementations and binary objects
 * 
 * 
 * <p>
 * Java class for BinDesc complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BinDesc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processorTarget" type="{http://www.ecoa.technology/bin-desc-1.0}ProcessorTarget"/>
 *         &lt;element name="binaryModule" type="{http://www.ecoa.technology/bin-desc-1.0}BinaryModule" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="componentImplementation" use="required" type="{http://www.ecoa.technology/bin-desc-1.0}NameId" />
 *       &lt;attribute name="insertionPolicy" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinDesc", propOrder = { "processorTarget", "binaryModules" })
@XmlRootElement(name = "binDesc")
public class BinDesc {

	@XmlElement(required = true)
	protected ProcessorTarget processorTarget;
	@XmlElement(name = "binaryModule", required = true)
	protected List<BinaryModule> binaryModules;
	@XmlAttribute(name = "componentImplementation", required = true)
	protected String componentImplementation;
	@XmlAttribute(name = "insertionPolicy")
	@XmlSchemaType(name = "anyURI")
	protected String insertionPolicy;

	/**
	 * Gets the value of the processorTarget property.
	 * 
	 * @return possible object is {@link ProcessorTarget }
	 * 
	 */
	public ProcessorTarget getProcessorTarget() {
		return processorTarget;
	}

	/**
	 * Sets the value of the processorTarget property.
	 * 
	 * @param value
	 *            allowed object is {@link ProcessorTarget }
	 * 
	 */
	public void setProcessorTarget(ProcessorTarget value) {
		this.processorTarget = value;
	}

	/**
	 * Gets the value of the binaryModules property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the binaryModules property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBinaryModules().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BinaryModule }
	 * 
	 * 
	 */
	public List<BinaryModule> getBinaryModules() {
		if (binaryModules == null) {
			binaryModules = new ArrayList<BinaryModule>();
		}
		return this.binaryModules;
	}

	/**
	 * Gets the value of the componentImplementation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComponentImplementation() {
		return componentImplementation;
	}

	/**
	 * Sets the value of the componentImplementation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComponentImplementation(String value) {
		this.componentImplementation = value;
	}

	/**
	 * Gets the value of the insertionPolicy property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInsertionPolicy() {
		return insertionPolicy;
	}

	/**
	 * Sets the value of the insertionPolicy property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInsertionPolicy(String value) {
		this.insertionPolicy = value;
	}

}
