//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:11:58 AM BST 
//

package com.iawg.ecoa.jaxbclasses.projectConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for APIConfigData complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="APIConfigData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="generateBodies" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="overwrite" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="generateTemplateCModules" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APIConfigData")
public class APIConfigData {

	@XmlAttribute(name = "generateBodies")
	protected Boolean generateBodies;
	@XmlAttribute(name = "overwrite")
	protected Boolean overwrite;
	@XmlAttribute(name = "generateTemplateCModules")
	protected Boolean generateTemplateCModules;

	/**
	 * Gets the value of the generateBodies property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isGenerateBodies() {
		if (generateBodies == null) {
			return true;
		} else {
			return generateBodies;
		}
	}

	/**
	 * Sets the value of the generateBodies property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setGenerateBodies(Boolean value) {
		this.generateBodies = value;
	}

	/**
	 * Gets the value of the overwrite property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isOverwrite() {
		if (overwrite == null) {
			return false;
		} else {
			return overwrite;
		}
	}

	/**
	 * Sets the value of the overwrite property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setOverwrite(Boolean value) {
		this.overwrite = value;
	}

	/**
	 * Gets the value of the generateTemplateCModules property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isGenerateTemplateCModules() {
		if (generateTemplateCModules == null) {
			return false;
		} else {
			return generateTemplateCModules;
		}
	}

	/**
	 * Sets the value of the generateTemplateCModules property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setGenerateTemplateCModules(Boolean value) {
		this.generateTemplateCModules = value;
	}

}
