//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:11:58 AM BST 
//

package com.iawg.ecoa.jaxbclasses.projectConfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EcoaProjectConfig complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EcoaProjectConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="toolConfig" type="{http://www.ecoa.technology/project-config-1.0}ConfigData" minOccurs="0"/>
 *         &lt;element ref="{http://www.ecoa.technology/project-1.0}ECOAProject" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EcoaProjectConfig", propOrder = { "toolConfig", "ecoaProject" })
@XmlRootElement(name = "ecoaProjectConfig")
public class EcoaProjectConfig {

	protected ConfigData toolConfig;
	@XmlElement(name = "ECOAProject", namespace = "http://www.ecoa.technology/project-1.0")
	protected ECOAProject ecoaProject;
	@XmlAttribute(name = "name", required = true)
	protected String name;

	/**
	 * Gets the value of the toolConfig property.
	 * 
	 * @return possible object is {@link ConfigData }
	 * 
	 */
	public ConfigData getToolConfig() {
		return toolConfig;
	}

	/**
	 * Sets the value of the toolConfig property.
	 * 
	 * @param value
	 *            allowed object is {@link ConfigData }
	 * 
	 */
	public void setToolConfig(ConfigData value) {
		this.toolConfig = value;
	}

	/**
	 * Gets the value of the ecoaProject property.
	 * 
	 * @return possible object is {@link ECOAProject }
	 * 
	 */
	public ECOAProject getECOAProject() {
		return ecoaProject;
	}

	/**
	 * Sets the value of the ecoaProject property.
	 * 
	 * @param value
	 *            allowed object is {@link ECOAProject }
	 * 
	 */
	public void setECOAProject(ECOAProject value) {
		this.ecoaProject = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
