//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:11:58 AM BST 
//

package com.iawg.ecoa.jaxbclasses.projectConfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.iawg.ecoa.jaxbclasses.projectConfig
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
	private static final String SEP_PATTERN_01 = "http://www.ecoa.technology/project-1.0";

	private final static QName _ECOAProjectComponentImplementations_QNAME = new QName(SEP_PATTERN_01, "componentImplementations");
	private final static QName _ECOAProjectLogicalSystem_QNAME = new QName(SEP_PATTERN_01, "logicalSystem");
	private final static QName _ECOAProjectImplementationAssembly_QNAME = new QName(SEP_PATTERN_01, "implementationAssembly");
	private final static QName _ECOAProjectTypes_QNAME = new QName(SEP_PATTERN_01, "types");
	private final static QName _ECOAProjectComponentDefinitions_QNAME = new QName(SEP_PATTERN_01, "componentDefinitions");
	private final static QName _ECOAProjectServiceDefinitions_QNAME = new QName(SEP_PATTERN_01, "serviceDefinitions");
	private final static QName _ECOAProjectDeploymentSchema_QNAME = new QName(SEP_PATTERN_01, "deploymentSchema");
	private final static QName _ECOAProjectInitialAssembly_QNAME = new QName(SEP_PATTERN_01, "initialAssembly");
	private final static QName _ECOAProjectOutputDirectory_QNAME = new QName(SEP_PATTERN_01, "outputDirectory");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.iawg.ecoa.jaxbclasses.projectConfig
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link EcoaProjectConfig }
	 * 
	 */
	public EcoaProjectConfig createEcoaProjectConfig() {
		return new EcoaProjectConfig();
	}

	/**
	 * Create an instance of {@link ConfigData }
	 * 
	 */
	public ConfigData createConfigData() {
		return new ConfigData();
	}

	/**
	 * Create an instance of {@link ECOAProject }
	 * 
	 */
	public ECOAProject createECOAProject() {
		return new ECOAProject();
	}

	/**
	 * Create an instance of {@link Files }
	 * 
	 */
	public Files createFiles() {
		return new Files();
	}

	/**
	 * Create an instance of {@link BinaryModuleImpl }
	 * 
	 */
	public BinaryModuleImpl createBinaryModuleImpl() {
		return new BinaryModuleImpl();
	}

	/**
	 * Create an instance of {@link PrecompiledComponents }
	 * 
	 */
	public PrecompiledComponents createPrecompiledComponents() {
		return new PrecompiledComponents();
	}

	/**
	 * Create an instance of {@link PlatformConfigData }
	 * 
	 */
	public PlatformConfigData createPlatformConfigData() {
		return new PlatformConfigData();
	}

	/**
	 * Create an instance of {@link ComponentImpl }
	 * 
	 */
	public ComponentImpl createComponentImpl() {
		return new ComponentImpl();
	}

	/**
	 * Create an instance of {@link APIConfigData }
	 * 
	 */
	public APIConfigData createAPIConfigData() {
		return new APIConfigData();
	}

	/**
	 * Create an instance of {@link Use }
	 * 
	 */
	public Use createUse() {
		return new Use();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Files }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "componentImplementations", scope = ECOAProject.class)
	public JAXBElement<Files> createECOAProjectComponentImplementations(Files value) {
		return new JAXBElement<Files>(_ECOAProjectComponentImplementations_QNAME, Files.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "logicalSystem", scope = ECOAProject.class)
	public JAXBElement<String> createECOAProjectLogicalSystem(String value) {
		return new JAXBElement<String>(_ECOAProjectLogicalSystem_QNAME, String.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "implementationAssembly", scope = ECOAProject.class)
	public JAXBElement<String> createECOAProjectImplementationAssembly(String value) {
		return new JAXBElement<String>(_ECOAProjectImplementationAssembly_QNAME, String.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Files }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "types", scope = ECOAProject.class)
	public JAXBElement<Files> createECOAProjectTypes(Files value) {
		return new JAXBElement<Files>(_ECOAProjectTypes_QNAME, Files.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Files }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "componentDefinitions", scope = ECOAProject.class)
	public JAXBElement<Files> createECOAProjectComponentDefinitions(Files value) {
		return new JAXBElement<Files>(_ECOAProjectComponentDefinitions_QNAME, Files.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Files }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "serviceDefinitions", scope = ECOAProject.class)
	public JAXBElement<Files> createECOAProjectServiceDefinitions(Files value) {
		return new JAXBElement<Files>(_ECOAProjectServiceDefinitions_QNAME, Files.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "deploymentSchema", scope = ECOAProject.class)
	public JAXBElement<String> createECOAProjectDeploymentSchema(String value) {
		return new JAXBElement<String>(_ECOAProjectDeploymentSchema_QNAME, String.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "initialAssembly", scope = ECOAProject.class)
	public JAXBElement<String> createECOAProjectInitialAssembly(String value) {
		return new JAXBElement<String>(_ECOAProjectInitialAssembly_QNAME, String.class, ECOAProject.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = SEP_PATTERN_01, name = "outputDirectory", scope = ECOAProject.class)
	public JAXBElement<String> createECOAProjectOutputDirectory(String value) {
		return new JAXBElement<String>(_ECOAProjectOutputDirectory_QNAME, String.class, ECOAProject.class, value);
	}

}
