//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:06 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step4aCompImpl;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

/**
 * Link between EVENT operations.
 * 
 * 
 * <p>
 * Java class for EventLink complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EventLink">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="senders" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;choice>
 *                     &lt;element name="service" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
 *                     &lt;element name="reference" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
 *                     &lt;element name="moduleInstance" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
 *                     &lt;element name="trigger" type="{http://www.ecoa.technology/implementation-1.0}OpRef_Trigger"/>
 *                     &lt;element name="dynamicTrigger" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
 *                     &lt;element name="external" type="{http://www.ecoa.technology/implementation-1.0}OpRef_External"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="receivers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;choice>
 *                     &lt;element name="service" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
 *                     &lt;element name="reference" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
 *                     &lt;element name="moduleInstance" type="{http://www.ecoa.technology/implementation-1.0}OpRefActivatableFifo"/>
 *                     &lt;element name="dynamicTrigger" type="{http://www.ecoa.technology/implementation-1.0}OpRefActivatingFifo"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventLink", propOrder = { "senders", "receivers" })
public class EventLink {

	protected EventLink.Senders senders;
	@XmlElement(required = true)
	protected EventLink.Receivers receivers;
	@XmlAttribute(name = "id")
	protected Integer id;

	/**
	 * Gets the value of the senders property.
	 * 
	 * @return possible object is {@link EventLink.Senders }
	 * 
	 */
	public EventLink.Senders getSenders() {
		return senders;
	}

	/**
	 * Sets the value of the senders property.
	 * 
	 * @param value
	 *            allowed object is {@link EventLink.Senders }
	 * 
	 */
	public void setSenders(EventLink.Senders value) {
		this.senders = value;
	}

	/**
	 * Gets the value of the receivers property.
	 * 
	 * @return possible object is {@link EventLink.Receivers }
	 * 
	 */
	public EventLink.Receivers getReceivers() {
		return receivers;
	}

	/**
	 * Sets the value of the receivers property.
	 * 
	 * @param value
	 *            allowed object is {@link EventLink.Receivers }
	 * 
	 */
	public void setReceivers(EventLink.Receivers value) {
		this.receivers = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setId(Integer value) {
		this.id = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence maxOccurs="unbounded">
	 *         &lt;choice>
	 *           &lt;element name="service" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
	 *           &lt;element name="reference" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
	 *           &lt;element name="moduleInstance" type="{http://www.ecoa.technology/implementation-1.0}OpRefActivatableFifo"/>
	 *           &lt;element name="dynamicTrigger" type="{http://www.ecoa.technology/implementation-1.0}OpRefActivatingFifo"/>
	 *         &lt;/choice>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "servicesAndReferencesAndModuleInstances" })
	public static class Receivers {

		@XmlElementRefs({ @XmlElementRef(name = "moduleInstance", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "service", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "reference", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "dynamicTrigger", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false) })
		protected List<JAXBElement<? extends OpRef>> servicesAndReferencesAndModuleInstances;

		/**
		 * Gets the value of the servicesAndReferencesAndModuleInstances
		 * property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the
		 * servicesAndReferencesAndModuleInstances property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getServicesAndReferencesAndModuleInstances().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link JAXBElement }{@code <}{@link OpRefActivatableFifo }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRef }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRef }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRefActivatingFifo }{@code >}
		 * 
		 * 
		 */
		public List<JAXBElement<? extends OpRef>> getServicesAndReferencesAndModuleInstances() {
			if (servicesAndReferencesAndModuleInstances == null) {
				servicesAndReferencesAndModuleInstances = new ArrayList<JAXBElement<? extends OpRef>>();
			}
			return this.servicesAndReferencesAndModuleInstances;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence maxOccurs="unbounded">
	 *         &lt;choice>
	 *           &lt;element name="service" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
	 *           &lt;element name="reference" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
	 *           &lt;element name="moduleInstance" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
	 *           &lt;element name="trigger" type="{http://www.ecoa.technology/implementation-1.0}OpRef_Trigger"/>
	 *           &lt;element name="dynamicTrigger" type="{http://www.ecoa.technology/implementation-1.0}OpRef"/>
	 *           &lt;element name="external" type="{http://www.ecoa.technology/implementation-1.0}OpRef_External"/>
	 *         &lt;/choice>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "servicesAndReferencesAndModuleInstances" })
	public static class Senders {

		@XmlElementRefs({ @XmlElementRef(name = "reference", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "external", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "moduleInstance", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "service", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "dynamicTrigger", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false), @XmlElementRef(name = "trigger", namespace = "http://www.ecoa.technology/implementation-1.0", type = JAXBElement.class, required = false) })
		protected List<JAXBElement<?>> servicesAndReferencesAndModuleInstances;

		/**
		 * Gets the value of the servicesAndReferencesAndModuleInstances
		 * property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the
		 * servicesAndReferencesAndModuleInstances property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getServicesAndReferencesAndModuleInstances().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link JAXBElement }{@code <}{@link OpRef }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRefExternal }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRef }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRef }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRefTrigger }{@code >}
		 * {@link JAXBElement }{@code <}{@link OpRef }{@code >}
		 * 
		 * 
		 */
		public List<JAXBElement<?>> getServicesAndReferencesAndModuleInstances() {
			if (servicesAndReferencesAndModuleInstances == null) {
				servicesAndReferencesAndModuleInstances = new ArrayList<JAXBElement<?>>();
			}
			return this.servicesAndReferencesAndModuleInstances;
		}

	}

}
