//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:06 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step4aCompImpl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Instance complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Instance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.ecoa.technology/implementation-1.0}NameId" />
 *       &lt;attribute name="moduleBehaviour" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="relativePriority" use="required" type="{http://www.ecoa.technology/implementation-1.0}RelativePriority" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Instance")
@XmlSeeAlso({ ModuleInstance.class, TriggerInstance.class, DynamicTriggerInstance.class })
public class Instance {

	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "moduleBehaviour")
	@XmlSchemaType(name = "anyURI")
	protected String moduleBehaviour;
	@XmlAttribute(name = "relativePriority", required = true)
	protected int relativePriority;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the moduleBehaviour property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModuleBehaviour() {
		return moduleBehaviour;
	}

	/**
	 * Sets the value of the moduleBehaviour property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModuleBehaviour(String value) {
		this.moduleBehaviour = value;
	}

	/**
	 * Gets the value of the relativePriority property.
	 * 
	 */
	public int getRelativePriority() {
		return relativePriority;
	}

	/**
	 * Sets the value of the relativePriority property.
	 * 
	 */
	public void setRelativePriority(int value) {
		this.relativePriority = value;
	}

}
