//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:04 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step2bServiceQOS;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Use of the "event" exchange mechanism.
 * 
 * 
 * <p>
 * Java class for Event complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="highestRate" type="{http://www.ecoa.technology/interface-qos-1.0}OperationRate" minOccurs="0"/>
 *         &lt;element name="lowestRate" type="{http://www.ecoa.technology/interface-qos-1.0}OperationRate" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.ecoa.technology/interface-qos-1.0}NameId" />
 *       &lt;attribute name="maxHandlingTime" type="{http://www.ecoa.technology/interface-qos-1.0}TimeDuration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = { "highestRate", "lowestRate" })
public class Event {

	protected OperationRate highestRate;
	protected OperationRate lowestRate;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "maxHandlingTime")
	protected Double maxHandlingTime;

	/**
	 * Gets the value of the highestRate property.
	 * 
	 * @return possible object is {@link OperationRate }
	 * 
	 */
	public OperationRate getHighestRate() {
		return highestRate;
	}

	/**
	 * Sets the value of the highestRate property.
	 * 
	 * @param value
	 *            allowed object is {@link OperationRate }
	 * 
	 */
	public void setHighestRate(OperationRate value) {
		this.highestRate = value;
	}

	/**
	 * Gets the value of the lowestRate property.
	 * 
	 * @return possible object is {@link OperationRate }
	 * 
	 */
	public OperationRate getLowestRate() {
		return lowestRate;
	}

	/**
	 * Sets the value of the lowestRate property.
	 * 
	 * @param value
	 *            allowed object is {@link OperationRate }
	 * 
	 */
	public void setLowestRate(OperationRate value) {
		this.lowestRate = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the maxHandlingTime property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMaxHandlingTime() {
		return maxHandlingTime;
	}

	/**
	 * Sets the value of the maxHandlingTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMaxHandlingTime(Double value) {
		this.maxHandlingTime = value;
	}

}
