//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:04 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step2bServiceQOS;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * A set of named operations.
 * 
 * <p>
 * Java class for Operations complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Operations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="data" type="{http://www.ecoa.technology/interface-qos-1.0}Data"/>
 *         &lt;element name="event" type="{http://www.ecoa.technology/interface-qos-1.0}Event"/>
 *         &lt;element name="requestresponse" type="{http://www.ecoa.technology/interface-qos-1.0}RequestResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Operations", propOrder = { "datasAndEventsAndRequestresponses" })
public class Operations {

	@XmlElements({ @XmlElement(name = "data", type = Data.class), @XmlElement(name = "event", type = Event.class), @XmlElement(name = "requestresponse", type = RequestResponse.class) })
	protected List<Object> datasAndEventsAndRequestresponses;

	/**
	 * Gets the value of the datasAndEventsAndRequestresponses property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the datasAndEventsAndRequestresponses
	 * property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDatasAndEventsAndRequestresponses().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Data }
	 * {@link Event } {@link RequestResponse }
	 * 
	 * 
	 */
	public List<Object> getDatasAndEventsAndRequestresponses() {
		if (datasAndEventsAndRequestresponses == null) {
			datasAndEventsAndRequestresponses = new ArrayList<Object>();
		}
		return this.datasAndEventsAndRequestresponses;
	}

}
