//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:15 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step5fUDP;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="platformId" use="required" type="{http://www.ecoa.technology/udpbinding-1.0}PlatformID" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="maxChannels" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="256" />
 *       &lt;attribute name="receivingPort" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="receivingMulticastAddress" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "platform")
public class Platform {

	@XmlAttribute(name = "platformId", required = true)
	protected long platformId;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "maxChannels")
	@XmlSchemaType(name = "positiveInteger")
	protected BigInteger maxChannels;
	@XmlAttribute(name = "receivingPort", required = true)
	@XmlSchemaType(name = "positiveInteger")
	protected BigInteger receivingPort;
	@XmlAttribute(name = "receivingMulticastAddress", required = true)
	protected String receivingMulticastAddress;

	/**
	 * Gets the value of the platformId property.
	 * 
	 */
	public long getPlatformId() {
		return platformId;
	}

	/**
	 * Sets the value of the platformId property.
	 * 
	 */
	public void setPlatformId(long value) {
		this.platformId = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the maxChannels property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getMaxChannels() {
		if (maxChannels == null) {
			return new BigInteger("256");
		} else {
			return maxChannels;
		}
	}

	/**
	 * Sets the value of the maxChannels property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setMaxChannels(BigInteger value) {
		this.maxChannels = value;
	}

	/**
	 * Gets the value of the receivingPort property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getReceivingPort() {
		return receivingPort;
	}

	/**
	 * Sets the value of the receivingPort property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setReceivingPort(BigInteger value) {
		this.receivingPort = value;
	}

	/**
	 * Gets the value of the receivingMulticastAddress property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReceivingMulticastAddress() {
		return receivingMulticastAddress;
	}

	/**
	 * Sets the value of the receivingMulticastAddress property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReceivingMulticastAddress(String value) {
		this.receivingMulticastAddress = value;
	}

}
