//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:00 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step0Types;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * A set of data types in a library
 * 
 * <p>
 * Java class for Library complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Library">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ecoa.technology/types-1.0}use" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="types" type="{http://www.ecoa.technology/types-1.0}DataTypes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Library", propOrder = { "uses", "types" })
@XmlRootElement(name = "library")
public class Library {

	@XmlElement(name = "use")
	protected List<Use> uses;
	@XmlElement(required = true)
	protected DataTypes types;

	/**
	 * Gets the value of the uses property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the uses property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getUses().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Use }
	 * 
	 * 
	 */
	public List<Use> getUses() {
		if (uses == null) {
			uses = new ArrayList<Use>();
		}
		return this.uses;
	}

	/**
	 * Gets the value of the types property.
	 * 
	 * @return possible object is {@link DataTypes }
	 * 
	 */
	public DataTypes getTypes() {
		return types;
	}

	/**
	 * Sets the value of the types property.
	 * 
	 * @param value
	 *            allowed object is {@link DataTypes }
	 * 
	 */
	public void setTypes(DataTypes value) {
		this.types = value;
	}

}
