//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:00 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step0Types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * A type based on a predefined type (simple or E_basic) with a name, min/max
 * constraints, and a unit.
 * 
 * 
 * <p>
 * Java class for Simple complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Simple">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://www.ecoa.technology/types-1.0}TypeQName" />
 *       &lt;attribute name="name" use="required" type="{http://www.ecoa.technology/types-1.0}TypeName" />
 *       &lt;attribute name="minRange" type="{http://www.ecoa.technology/types-1.0}ConstantReferenceOrValue" />
 *       &lt;attribute name="maxRange" type="{http://www.ecoa.technology/types-1.0}ConstantReferenceOrValue" />
 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="precision" type="{http://www.ecoa.technology/types-1.0}ConstantReferenceOrValue" />
 *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Simple")
public class Simple {

	@XmlAttribute(name = "type", required = true)
	protected String type;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "minRange")
	protected String minRange;
	@XmlAttribute(name = "maxRange")
	protected String maxRange;
	@XmlAttribute(name = "unit")
	protected String unit;
	@XmlAttribute(name = "precision")
	protected String precision;
	@XmlAttribute(name = "comment")
	protected String comment;

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the minRange property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMinRange() {
		return minRange;
	}

	/**
	 * Sets the value of the minRange property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMinRange(String value) {
		this.minRange = value;
	}

	/**
	 * Gets the value of the maxRange property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMaxRange() {
		return maxRange;
	}

	/**
	 * Sets the value of the maxRange property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMaxRange(String value) {
		this.maxRange = value;
	}

	/**
	 * Gets the value of the unit property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * Sets the value of the unit property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUnit(String value) {
		this.unit = value;
	}

	/**
	 * Gets the value of the precision property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPrecision() {
		return precision;
	}

	/**
	 * Sets the value of the precision property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPrecision(String value) {
		this.precision = value;
	}

	/**
	 * Gets the value of the comment property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * Sets the value of the comment property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComment(String value) {
		this.comment = value;
	}

}
