//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.10 at 03:45:14 PM IST 
//

package tech.ecoa.osets.model.lsys;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="logicalComputingPlatform" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="logicalComputingNode" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="endianess">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="type" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="BIG"/>
 *                                           &lt;enumeration value="LITTLE"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="logicalProcessors" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="stepDuration">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="nanoSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="os">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="fastos"/>
 *                                           &lt;enumeration value="linux"/>
 *                                           &lt;enumeration value="ima-integrity"/>
 *                                           &lt;enumeration value="ims-vxworks"/>
 *                                           &lt;enumeration value="integrity"/>
 *                                           &lt;enumeration value="pikeos"/>
 *                                           &lt;enumeration value="rtems"/>
 *                                           &lt;enumeration value="vxworks"/>
 *                                           &lt;enumeration value="vxworks-arinc653"/>
 *                                           &lt;enumeration value="vxworks-cert"/>
 *                                           &lt;enumeration value="windows"/>
 *                                           &lt;enumeration value="zephyr"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                     &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="availableMemory">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="gigaBytes" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="moduleSwitchTime">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="logicalComputingNodeLinks" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="link" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="throughput">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="latency">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
 *                                     &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="logicalComputingPlatformLinks" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="link" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="throughput">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="latency">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
 *                           &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "logicalComputingPlatform", "logicalComputingPlatformLinks" })
@XmlRootElement(name = "logicalSystem")
public class LogicalSystem {

	@XmlElement(required = true)
	protected List<LogicalSystem.LogicalComputingPlatform> logicalComputingPlatform;
	protected List<LogicalSystem.LogicalComputingPlatformLinks> logicalComputingPlatformLinks;
	@XmlAttribute(name = "id", required = true)
	protected String id;

	/**
	 * Gets the value of the logicalComputingPlatform property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the logicalComputingPlatform property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLogicalComputingPlatform().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link LogicalSystem.LogicalComputingPlatform }
	 * 
	 * 
	 */
	public List<LogicalSystem.LogicalComputingPlatform> getLogicalComputingPlatform() {
		if (logicalComputingPlatform == null) {
			logicalComputingPlatform = new ArrayList<LogicalSystem.LogicalComputingPlatform>();
		}
		return this.logicalComputingPlatform;
	}

	/**
	 * Gets the value of the logicalComputingPlatformLinks property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the logicalComputingPlatformLinks property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLogicalComputingPlatformLinks().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link LogicalSystem.LogicalComputingPlatformLinks }
	 * 
	 * 
	 */
	public List<LogicalSystem.LogicalComputingPlatformLinks> getLogicalComputingPlatformLinks() {
		if (logicalComputingPlatformLinks == null) {
			logicalComputingPlatformLinks = new ArrayList<LogicalSystem.LogicalComputingPlatformLinks>();
		}
		return this.logicalComputingPlatformLinks;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="logicalComputingNode" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="endianess">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="type" use="required">
	 *                             &lt;simpleType>
	 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *                                 &lt;enumeration value="BIG"/>
	 *                                 &lt;enumeration value="LITTLE"/>
	 *                               &lt;/restriction>
	 *                             &lt;/simpleType>
	 *                           &lt;/attribute>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="logicalProcessors" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="stepDuration">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="nanoSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="os">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="name" use="required">
	 *                             &lt;simpleType>
	 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *                                 &lt;enumeration value="fastos"/>
	 *                                 &lt;enumeration value="linux"/>
	 *                                 &lt;enumeration value="ima-integrity"/>
	 *                                 &lt;enumeration value="ims-vxworks"/>
	 *                                 &lt;enumeration value="integrity"/>
	 *                                 &lt;enumeration value="pikeos"/>
	 *                                 &lt;enumeration value="rtems"/>
	 *                                 &lt;enumeration value="vxworks"/>
	 *                                 &lt;enumeration value="vxworks-arinc653"/>
	 *                                 &lt;enumeration value="vxworks-cert"/>
	 *                                 &lt;enumeration value="windows"/>
	 *                                 &lt;enumeration value="zephyr"/>
	 *                               &lt;/restriction>
	 *                             &lt;/simpleType>
	 *                           &lt;/attribute>
	 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="availableMemory">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="gigaBytes" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="moduleSwitchTime">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="logicalComputingNodeLinks" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="link" maxOccurs="unbounded">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="throughput">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                             &lt;element name="latency">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                           &lt;attribute name="id" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
	 *                           &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="id" use="required" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "logicalComputingNode", "logicalComputingNodeLinks" })
	public static class LogicalComputingPlatform {

		@XmlElement(required = true)
		protected List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNode> logicalComputingNode;
		protected List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks> logicalComputingNodeLinks;
		@XmlAttribute(name = "id", required = true)
		protected String id;

		/**
		 * Gets the value of the logicalComputingNode property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the logicalComputingNode property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getLogicalComputingNode().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode }
		 * 
		 * 
		 */
		public List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNode> getLogicalComputingNode() {
			if (logicalComputingNode == null) {
				logicalComputingNode = new ArrayList<LogicalSystem.LogicalComputingPlatform.LogicalComputingNode>();
			}
			return this.logicalComputingNode;
		}

		/**
		 * Gets the value of the logicalComputingNodeLinks property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the logicalComputingNodeLinks property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getLogicalComputingNodeLinks().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks }
		 * 
		 * 
		 */
		public List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks> getLogicalComputingNodeLinks() {
			if (logicalComputingNodeLinks == null) {
				logicalComputingNodeLinks = new ArrayList<LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks>();
			}
			return this.logicalComputingNodeLinks;
		}

		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getId() {
			return id;
		}

		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setId(String value) {
			this.id = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="endianess">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="type" use="required">
		 *                   &lt;simpleType>
		 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
		 *                       &lt;enumeration value="BIG"/>
		 *                       &lt;enumeration value="LITTLE"/>
		 *                     &lt;/restriction>
		 *                   &lt;/simpleType>
		 *                 &lt;/attribute>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="logicalProcessors" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="stepDuration">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="nanoSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="os">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="name" use="required">
		 *                   &lt;simpleType>
		 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
		 *                       &lt;enumeration value="fastos"/>
		 *                       &lt;enumeration value="linux"/>
		 *                       &lt;enumeration value="ima-integrity"/>
		 *                       &lt;enumeration value="ims-vxworks"/>
		 *                       &lt;enumeration value="integrity"/>
		 *                       &lt;enumeration value="pikeos"/>
		 *                       &lt;enumeration value="rtems"/>
		 *                       &lt;enumeration value="vxworks"/>
		 *                       &lt;enumeration value="vxworks-arinc653"/>
		 *                       &lt;enumeration value="vxworks-cert"/>
		 *                       &lt;enumeration value="windows"/>
		 *                       &lt;enumeration value="zephyr"/>
		 *                     &lt;/restriction>
		 *                   &lt;/simpleType>
		 *                 &lt;/attribute>
		 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="availableMemory">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="gigaBytes" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="moduleSwitchTime">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "endianess", "logicalProcessors", "os", "availableMemory", "moduleSwitchTime" })
		public static class LogicalComputingNode {

			@XmlElement(required = true)
			protected LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess endianess;
			@XmlElement(required = true)
			protected List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors> logicalProcessors;
			@XmlElement(required = true)
			protected LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os os;
			@XmlElement(required = true)
			protected LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory availableMemory;
			@XmlElement(required = true)
			protected LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime moduleSwitchTime;
			@XmlAttribute(name = "id", required = true)
			protected String id;

			/**
			 * Gets the value of the endianess property.
			 * 
			 * @return possible object is
			 *         {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess }
			 * 
			 */
			public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess getEndianess() {
				return endianess;
			}

			/**
			 * Sets the value of the endianess property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess }
			 * 
			 */
			public void setEndianess(LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess value) {
				this.endianess = value;
			}

			/**
			 * Gets the value of the logicalProcessors property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the logicalProcessors property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getLogicalProcessors().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors }
			 * 
			 * 
			 */
			public List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors> getLogicalProcessors() {
				if (logicalProcessors == null) {
					logicalProcessors = new ArrayList<LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors>();
				}
				return this.logicalProcessors;
			}

			/**
			 * Gets the value of the os property.
			 * 
			 * @return possible object is
			 *         {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os }
			 * 
			 */
			public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os getOs() {
				return os;
			}

			/**
			 * Sets the value of the os property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os }
			 * 
			 */
			public void setOs(LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os value) {
				this.os = value;
			}

			/**
			 * Gets the value of the availableMemory property.
			 * 
			 * @return possible object is
			 *         {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory }
			 * 
			 */
			public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory getAvailableMemory() {
				return availableMemory;
			}

			/**
			 * Sets the value of the availableMemory property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory }
			 * 
			 */
			public void setAvailableMemory(LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory value) {
				this.availableMemory = value;
			}

			/**
			 * Gets the value of the moduleSwitchTime property.
			 * 
			 * @return possible object is
			 *         {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime }
			 * 
			 */
			public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime getModuleSwitchTime() {
				return moduleSwitchTime;
			}

			/**
			 * Sets the value of the moduleSwitchTime property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime }
			 * 
			 */
			public void setModuleSwitchTime(LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime value) {
				this.moduleSwitchTime = value;
			}

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="gigaBytes" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class AvailableMemory {

				@XmlAttribute(name = "gigaBytes", required = true)
				protected BigInteger gigaBytes;

				/**
				 * Gets the value of the gigaBytes property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getGigaBytes() {
					return gigaBytes;
				}

				/**
				 * Sets the value of the gigaBytes property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setGigaBytes(BigInteger value) {
					this.gigaBytes = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="type" use="required">
			 *         &lt;simpleType>
			 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
			 *             &lt;enumeration value="BIG"/>
			 *             &lt;enumeration value="LITTLE"/>
			 *           &lt;/restriction>
			 *         &lt;/simpleType>
			 *       &lt;/attribute>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class Endianess {

				@XmlAttribute(name = "type", required = true)
				protected String type;

				/**
				 * Gets the value of the type property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getType() {
					return type;
				}

				/**
				 * Sets the value of the type property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setType(String value) {
					this.type = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="stepDuration">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="nanoSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "stepDuration" })
			public static class LogicalProcessors {

				@XmlElement(required = true)
				protected LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration stepDuration;
				@XmlAttribute(name = "type", required = true)
				protected String type;
				@XmlAttribute(name = "number", required = true)
				protected BigInteger number;

				/**
				 * Gets the value of the stepDuration property.
				 * 
				 * @return possible object is
				 *         {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration }
				 * 
				 */
				public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration getStepDuration() {
					return stepDuration;
				}

				/**
				 * Sets the value of the stepDuration property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration }
				 * 
				 */
				public void setStepDuration(LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration value) {
					this.stepDuration = value;
				}

				/**
				 * Gets the value of the type property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getType() {
					return type;
				}

				/**
				 * Sets the value of the type property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setType(String value) {
					this.type = value;
				}

				/**
				 * Gets the value of the number property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getNumber() {
					return number;
				}

				/**
				 * Sets the value of the number property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setNumber(BigInteger value) {
					this.number = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="nanoSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class StepDuration {

					@XmlAttribute(name = "nanoSeconds", required = true)
					protected BigInteger nanoSeconds;

					/**
					 * Gets the value of the nanoSeconds property.
					 * 
					 * @return possible object is {@link BigInteger }
					 * 
					 */
					public BigInteger getNanoSeconds() {
						return nanoSeconds;
					}

					/**
					 * Sets the value of the nanoSeconds property.
					 * 
					 * @param value
					 *            allowed object is {@link BigInteger }
					 * 
					 */
					public void setNanoSeconds(BigInteger value) {
						this.nanoSeconds = value;
					}

				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class ModuleSwitchTime {

				@XmlAttribute(name = "microSeconds", required = true)
				protected BigInteger microSeconds;

				/**
				 * Gets the value of the microSeconds property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getMicroSeconds() {
					return microSeconds;
				}

				/**
				 * Sets the value of the microSeconds property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setMicroSeconds(BigInteger value) {
					this.microSeconds = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="name" use="required">
			 *         &lt;simpleType>
			 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
			 *             &lt;enumeration value="fastos"/>
			 *             &lt;enumeration value="linux"/>
			 *             &lt;enumeration value="ima-integrity"/>
			 *             &lt;enumeration value="ims-vxworks"/>
			 *             &lt;enumeration value="integrity"/>
			 *             &lt;enumeration value="pikeos"/>
			 *             &lt;enumeration value="rtems"/>
			 *             &lt;enumeration value="vxworks"/>
			 *             &lt;enumeration value="vxworks-arinc653"/>
			 *             &lt;enumeration value="vxworks-cert"/>
			 *             &lt;enumeration value="windows"/>
			 *             &lt;enumeration value="zephyr"/>
			 *           &lt;/restriction>
			 *         &lt;/simpleType>
			 *       &lt;/attribute>
			 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class Os {

				@XmlAttribute(name = "name", required = true)
				protected String name;
				@XmlAttribute(name = "version")
				protected String version;

				/**
				 * Gets the value of the name property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getName() {
					return name;
				}

				/**
				 * Sets the value of the name property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setName(String value) {
					this.name = value;
				}

				/**
				 * Gets the value of the version property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getVersion() {
					return version;
				}

				/**
				 * Sets the value of the version property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setVersion(String value) {
					this.version = value;
				}

			}

		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="link" maxOccurs="unbounded">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="throughput">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                   &lt;element name="latency">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *                 &lt;attribute name="id" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
		 *                 &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "link" })
		public static class LogicalComputingNodeLinks {

			@XmlElement(required = true)
			protected List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link> link;

			/**
			 * Gets the value of the link property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned
			 * list will be present inside the JAXB object. This is why there is
			 * not a <CODE>set</CODE> method for the link property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getLink().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Objects of the following type(s) are allowed in the list
			 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link }
			 * 
			 * 
			 */
			public List<LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link> getLink() {
				if (link == null) {
					link = new ArrayList<LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link>();
				}
				return this.link;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="throughput">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *         &lt;element name="latency">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *       &lt;attribute name="id" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
			 *       &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "throughput", "latency" })
			public static class Link {

				@XmlElement(required = true)
				protected LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput throughput;
				@XmlElement(required = true)
				protected LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency latency;
				@XmlAttribute(name = "id")
				protected String id;
				@XmlAttribute(name = "to", required = true)
				protected String to;
				@XmlAttribute(name = "from", required = true)
				protected String from;

				/**
				 * Gets the value of the throughput property.
				 * 
				 * @return possible object is
				 *         {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput }
				 * 
				 */
				public LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput getThroughput() {
					return throughput;
				}

				/**
				 * Sets the value of the throughput property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput }
				 * 
				 */
				public void setThroughput(LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput value) {
					this.throughput = value;
				}

				/**
				 * Gets the value of the latency property.
				 * 
				 * @return possible object is
				 *         {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency }
				 * 
				 */
				public LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency getLatency() {
					return latency;
				}

				/**
				 * Sets the value of the latency property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency }
				 * 
				 */
				public void setLatency(LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency value) {
					this.latency = value;
				}

				/**
				 * Gets the value of the id property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getId() {
					return id;
				}

				/**
				 * Sets the value of the id property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setId(String value) {
					this.id = value;
				}

				/**
				 * Gets the value of the to property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getTo() {
					return to;
				}

				/**
				 * Sets the value of the to property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setTo(String value) {
					this.to = value;
				}

				/**
				 * Gets the value of the from property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getFrom() {
					return from;
				}

				/**
				 * Sets the value of the from property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setFrom(String value) {
					this.from = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Latency {

					@XmlAttribute(name = "microSeconds", required = true)
					protected BigInteger microSeconds;

					/**
					 * Gets the value of the microSeconds property.
					 * 
					 * @return possible object is {@link BigInteger }
					 * 
					 */
					public BigInteger getMicroSeconds() {
						return microSeconds;
					}

					/**
					 * Sets the value of the microSeconds property.
					 * 
					 * @param value
					 *            allowed object is {@link BigInteger }
					 * 
					 */
					public void setMicroSeconds(BigInteger value) {
						this.microSeconds = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "")
				public static class Throughput {

					@XmlAttribute(name = "megaBytesPerSecond", required = true)
					protected BigInteger megaBytesPerSecond;

					/**
					 * Gets the value of the megaBytesPerSecond property.
					 * 
					 * @return possible object is {@link BigInteger }
					 * 
					 */
					public BigInteger getMegaBytesPerSecond() {
						return megaBytesPerSecond;
					}

					/**
					 * Sets the value of the megaBytesPerSecond property.
					 * 
					 * @param value
					 *            allowed object is {@link BigInteger }
					 * 
					 */
					public void setMegaBytesPerSecond(BigInteger value) {
						this.megaBytesPerSecond = value;
					}

				}

			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="link" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="throughput">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="latency">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="id" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
	 *                 &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "link" })
	public static class LogicalComputingPlatformLinks {

		@XmlElement(required = true)
		protected List<LogicalSystem.LogicalComputingPlatformLinks.Link> link;

		/**
		 * Gets the value of the link property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the link property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getLink().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link LogicalSystem.LogicalComputingPlatformLinks.Link }
		 * 
		 * 
		 */
		public List<LogicalSystem.LogicalComputingPlatformLinks.Link> getLink() {
			if (link == null) {
				link = new ArrayList<LogicalSystem.LogicalComputingPlatformLinks.Link>();
			}
			return this.link;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="throughput">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="latency">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="id" type="{http://www.ecoa.technology/logicalsystem-1.0}NameId" />
		 *       &lt;attribute name="to" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="from" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "throughput", "latency" })
		public static class Link {

			@XmlElement(required = true)
			protected LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput throughput;
			@XmlElement(required = true)
			protected LogicalSystem.LogicalComputingPlatformLinks.Link.Latency latency;
			@XmlAttribute(name = "id")
			protected String id;
			@XmlAttribute(name = "to", required = true)
			protected String to;
			@XmlAttribute(name = "from", required = true)
			protected String from;

			/**
			 * Gets the value of the throughput property.
			 * 
			 * @return possible object is
			 *         {@link LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput }
			 * 
			 */
			public LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput getThroughput() {
				return throughput;
			}

			/**
			 * Sets the value of the throughput property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput }
			 * 
			 */
			public void setThroughput(LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput value) {
				this.throughput = value;
			}

			/**
			 * Gets the value of the latency property.
			 * 
			 * @return possible object is
			 *         {@link LogicalSystem.LogicalComputingPlatformLinks.Link.Latency }
			 * 
			 */
			public LogicalSystem.LogicalComputingPlatformLinks.Link.Latency getLatency() {
				return latency;
			}

			/**
			 * Sets the value of the latency property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link LogicalSystem.LogicalComputingPlatformLinks.Link.Latency }
			 * 
			 */
			public void setLatency(LogicalSystem.LogicalComputingPlatformLinks.Link.Latency value) {
				this.latency = value;
			}

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * Gets the value of the to property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getTo() {
				return to;
			}

			/**
			 * Sets the value of the to property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setTo(String value) {
				this.to = value;
			}

			/**
			 * Gets the value of the from property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getFrom() {
				return from;
			}

			/**
			 * Sets the value of the from property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setFrom(String value) {
				this.from = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="microSeconds" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class Latency {

				@XmlAttribute(name = "microSeconds", required = true)
				protected BigInteger microSeconds;

				/**
				 * Gets the value of the microSeconds property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getMicroSeconds() {
					return microSeconds;
				}

				/**
				 * Sets the value of the microSeconds property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setMicroSeconds(BigInteger value) {
					this.microSeconds = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;attribute name="megaBytesPerSecond" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "")
			public static class Throughput {

				@XmlAttribute(name = "megaBytesPerSecond", required = true)
				protected BigInteger megaBytesPerSecond;

				/**
				 * Gets the value of the megaBytesPerSecond property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getMegaBytesPerSecond() {
					return megaBytesPerSecond;
				}

				/**
				 * Sets the value of the megaBytesPerSecond property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setMegaBytesPerSecond(BigInteger value) {
					this.megaBytesPerSecond = value;
				}

			}

		}

	}

}
