//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.10 at 03:45:14 PM IST 
//

package tech.ecoa.osets.model.lsys;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the tech.ecoa.osets.model.lsys package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: tech.ecoa.osets.model.lsys
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link LogicalSystem }
	 * 
	 */
	public LogicalSystem createLogicalSystem() {
		return new LogicalSystem();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatformLinks }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatformLinks createLogicalSystemLogicalComputingPlatformLinks() {
		return new LogicalSystem.LogicalComputingPlatformLinks();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatformLinks.Link }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatformLinks.Link createLogicalSystemLogicalComputingPlatformLinksLink() {
		return new LogicalSystem.LogicalComputingPlatformLinks.Link();
	}

	/**
	 * Create an instance of {@link LogicalSystem.LogicalComputingPlatform }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform createLogicalSystemLogicalComputingPlatform() {
		return new LogicalSystem.LogicalComputingPlatform();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks createLogicalSystemLogicalComputingPlatformLogicalComputingNodeLinks() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link createLogicalSystemLogicalComputingPlatformLogicalComputingNodeLinksLink() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode createLogicalSystemLogicalComputingPlatformLogicalComputingNode() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNode();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors createLogicalSystemLogicalComputingPlatformLogicalComputingNodeLogicalProcessors() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors();
	}

	/**
	 * Create an instance of {@link Use }
	 * 
	 */
	public Use createUse() {
		return new Use();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput createLogicalSystemLogicalComputingPlatformLinksLinkThroughput() {
		return new LogicalSystem.LogicalComputingPlatformLinks.Link.Throughput();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatformLinks.Link.Latency }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatformLinks.Link.Latency createLogicalSystemLogicalComputingPlatformLinksLinkLatency() {
		return new LogicalSystem.LogicalComputingPlatformLinks.Link.Latency();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput createLogicalSystemLogicalComputingPlatformLogicalComputingNodeLinksLinkThroughput() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Throughput();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency createLogicalSystemLogicalComputingPlatformLogicalComputingNodeLinksLinkLatency() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNodeLinks.Link.Latency();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess createLogicalSystemLogicalComputingPlatformLogicalComputingNodeEndianess() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Endianess();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os createLogicalSystemLogicalComputingPlatformLogicalComputingNodeOs() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.Os();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory createLogicalSystemLogicalComputingPlatformLogicalComputingNodeAvailableMemory() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.AvailableMemory();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime createLogicalSystemLogicalComputingPlatformLogicalComputingNodeModuleSwitchTime() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.ModuleSwitchTime();
	}

	/**
	 * Create an instance of
	 * {@link LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration }
	 * 
	 */
	public LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration createLogicalSystemLogicalComputingPlatformLogicalComputingNodeLogicalProcessorsStepDuration() {
		return new LogicalSystem.LogicalComputingPlatform.LogicalComputingNode.LogicalProcessors.StepDuration();
	}

}
