//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 02:26:48 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/ns/opencsa/sca/200912", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tech.ecoa.osets.model.cdef;
