//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.02 at 02:26:48 PM IST 
//

package tech.ecoa.osets.model.cdef;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Reference complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Reference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/opencsa/sca/200912}Contract">
 *       &lt;attribute name="multiplicity" use="required" type="{http://docs.oasis-open.org/ns/opencsa/sca/200912}Multiplicity" />
 *       &lt;attribute name="promote" use="required" type="{http://docs.oasis-open.org/ns/opencsa/sca/200912}listOfAnyURIs" />
 *       &lt;attribute ref="{http://www.ecoa.technology/sca}promoteRankList use="required""/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reference")
public class Reference extends Contract {

	@XmlAttribute(name = "multiplicity", required = true)
	protected String multiplicity;
	@XmlAttribute(name = "promote", required = true)
	protected List<String> promote;
	@XmlAttribute(name = "promoteRankList", namespace = "http://www.ecoa.technology/sca", required = true)
	protected List<BigInteger> promoteRankList;

	/**
	 * Gets the value of the multiplicity property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMultiplicity() {
		return multiplicity;
	}

	/**
	 * Sets the value of the multiplicity property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMultiplicity(String value) {
		this.multiplicity = value;
	}

	/**
	 * Gets the value of the promote property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the promote property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPromote().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getPromote() {
		if (promote == null) {
			promote = new ArrayList<String>();
		}
		return this.promote;
	}

	/**
	 * Gets the value of the promoteRankList property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the promoteRankList property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPromoteRankList().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BigInteger }
	 * 
	 * 
	 */
	public List<BigInteger> getPromoteRankList() {
		if (promoteRankList == null) {
			promoteRankList = new ArrayList<BigInteger>();
		}
		return this.promoteRankList;
	}

}
