//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 09:12:16 AM IST 
//

package tech.ecoa.osets.model.intf.qos;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Use of the "versionned data" exchange mechanism.
 * 
 * 
 * <p>
 * Java class for Data complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="highestRate" type="{http://www.ecoa.technology/interface-qos-1.0}OperationRate" minOccurs="0"/>
 *         &lt;element name="lowestRate" type="{http://www.ecoa.technology/interface-qos-1.0}OperationRate" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.ecoa.technology/interface-qos-1.0}NameId" />
 *       &lt;attribute name="maxAgeing" type="{http://www.ecoa.technology/interface-qos-1.0}TimeDuration" />
 *       &lt;attribute name="notificationMaxHandlingTime" type="{http://www.ecoa.technology/interface-qos-1.0}TimeDuration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Data", propOrder = { "highestRate", "lowestRate" })
public class Data {

	protected OperationRate highestRate;
	protected OperationRate lowestRate;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "maxAgeing")
	protected Double maxAgeing;
	@XmlAttribute(name = "notificationMaxHandlingTime")
	protected Double notificationMaxHandlingTime;

	/**
	 * Gets the value of the highestRate property.
	 * 
	 * @return possible object is {@link OperationRate }
	 * 
	 */
	public OperationRate getHighestRate() {
		return highestRate;
	}

	/**
	 * Sets the value of the highestRate property.
	 * 
	 * @param value
	 *            allowed object is {@link OperationRate }
	 * 
	 */
	public void setHighestRate(OperationRate value) {
		this.highestRate = value;
	}

	/**
	 * Gets the value of the lowestRate property.
	 * 
	 * @return possible object is {@link OperationRate }
	 * 
	 */
	public OperationRate getLowestRate() {
		return lowestRate;
	}

	/**
	 * Sets the value of the lowestRate property.
	 * 
	 * @param value
	 *            allowed object is {@link OperationRate }
	 * 
	 */
	public void setLowestRate(OperationRate value) {
		this.lowestRate = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the maxAgeing property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getMaxAgeing() {
		return maxAgeing;
	}

	/**
	 * Sets the value of the maxAgeing property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setMaxAgeing(Double value) {
		this.maxAgeing = value;
	}

	/**
	 * Gets the value of the notificationMaxHandlingTime property.
	 * 
	 * @return possible object is {@link Double }
	 * 
	 */
	public Double getNotificationMaxHandlingTime() {
		return notificationMaxHandlingTime;
	}

	/**
	 * Sets the value of the notificationMaxHandlingTime property.
	 * 
	 * @param value
	 *            allowed object is {@link Double }
	 * 
	 */
	public void setNotificationMaxHandlingTime(Double value) {
		this.notificationMaxHandlingTime = value;
	}

}
