//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:13 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step5dContribution;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ComponentType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ComponentType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/opencsa/sca/200912}CommonExtensionBase">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="service">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://docs.oasis-open.org/ns/opencsa/sca/200912}ComponentService">
 *                   &lt;sequence>
 *                     &lt;sequence>
 *                       &lt;element ref="{http://www.ecoa.technology/sca}interface"/>
 *                     &lt;/sequence>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="reference" type="{http://docs.oasis-open.org/ns/opencsa/sca/200912}ComponentTypeReference"/>
 *           &lt;element name="property" type="{http://docs.oasis-open.org/ns/opencsa/sca/200912}Property"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentType", propOrder = { "servicesAndReferencesAndProperties" })
@XmlRootElement(name = "componentType")
public class ComponentType extends CommonExtensionBase {

	@XmlElements({ @XmlElement(name = "service", type = ComponentType.Service.class), @XmlElement(name = "reference", type = ComponentTypeReference.class), @XmlElement(name = "property", type = Property.class) })
	protected List<Object> servicesAndReferencesAndProperties;

	/**
	 * Gets the value of the servicesAndReferencesAndProperties property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the servicesAndReferencesAndProperties
	 * property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getServicesAndReferencesAndProperties().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ComponentType.Service } {@link ComponentTypeReference }
	 * {@link Property }
	 * 
	 * 
	 */
	public List<Object> getServicesAndReferencesAndProperties() {
		if (servicesAndReferencesAndProperties == null) {
			servicesAndReferencesAndProperties = new ArrayList<Object>();
		}
		return this.servicesAndReferencesAndProperties;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://docs.oasis-open.org/ns/opencsa/sca/200912}ComponentService">
	 *       &lt;sequence>
	 *         &lt;sequence>
	 *           &lt;element ref="{http://www.ecoa.technology/sca}interface"/>
	 *         &lt;/sequence>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Service extends ComponentService {

	}

}
