//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:13 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step5dContribution;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Property complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Property">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/opencsa/sca/200912}SCAPropertyBase">
 *       &lt;attribute name="mustSupply" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Property")
public class Property extends SCAPropertyBase {

	@XmlAttribute(name = "mustSupply")
	protected Boolean mustSupply;

	/**
	 * Gets the value of the mustSupply property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isMustSupply() {
		if (mustSupply == null) {
			return false;
		} else {
			return mustSupply;
		}
	}

	/**
	 * Sets the value of the mustSupply property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setMustSupply(Boolean value) {
		this.mustSupply = value;
	}

}
