//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:02 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step2aCompDefs;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

/**
 * <p>
 * Java class for Wire complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Wire">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/opencsa/sca/200912}CommonExtensionBase">
 *       &lt;sequence>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute ref="{http://www.ecoa.technology/sca}rank use="required""/>
 *       &lt;attribute ref="{http://www.ecoa.technology/sca}allEventsMulticasted"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Wire", propOrder = { "anies" })
public class Wire extends CommonExtensionBase {

	@XmlAnyElement
	protected List<Element> anies;
	@XmlAttribute(name = "source", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String source;
	@XmlAttribute(name = "target", required = true)
	@XmlSchemaType(name = "anyURI")
	protected String target;
	@XmlAttribute(name = "rank", namespace = "http://www.ecoa.technology/sca", required = true)
	@XmlSchemaType(name = "positiveInteger")
	protected BigInteger rank;
	@XmlAttribute(name = "allEventsMulticasted", namespace = "http://www.ecoa.technology/sca")
	protected Boolean allEventsMulticasted;

	/**
	 * Gets the value of the anies property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the anies property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAnies().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Element }
	 * 
	 * 
	 */
	public List<Element> getAnies() {
		if (anies == null) {
			anies = new ArrayList<Element>();
		}
		return this.anies;
	}

	/**
	 * Gets the value of the source property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSource(String value) {
		this.source = value;
	}

	/**
	 * Gets the value of the target property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * Sets the value of the target property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTarget(String value) {
		this.target = value;
	}

	/**
	 * Gets the value of the rank property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getRank() {
		return rank;
	}

	/**
	 * Sets the value of the rank property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setRank(BigInteger value) {
		this.rank = value;
	}

	/**
	 * Gets the value of the allEventsMulticasted property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public boolean isAllEventsMulticasted() {
		if (allEventsMulticasted == null) {
			return false;
		} else {
			return allEventsMulticasted;
		}
	}

	/**
	 * Sets the value of the allEventsMulticasted property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setAllEventsMulticasted(Boolean value) {
		this.allEventsMulticasted = value;
	}

}
