//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.20 at 08:12:10 AM BST 
//

package com.iawg.ecoa.jaxbclasses.step5bFinalAssembly;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for Component complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Component">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/opencsa/sca/200912}CommonExtensionBase">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/opencsa/sca/200912}implementation"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="service" type="{http://docs.oasis-open.org/ns/opencsa/sca/200912}ComponentService"/>
 *           &lt;element name="reference" type="{http://docs.oasis-open.org/ns/opencsa/sca/200912}ComponentReference"/>
 *           &lt;element name="property" type="{http://docs.oasis-open.org/ns/opencsa/sca/200912}PropertyValue"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Component", propOrder = { "implementation", "servicesAndReferencesAndProperties" })
public class Component extends CommonExtensionBase {

	@XmlElementRef(name = "implementation", namespace = "http://docs.oasis-open.org/ns/opencsa/sca/200912", type = JAXBElement.class)
	protected JAXBElement<? extends Implementation> implementation;
	@XmlElements({ @XmlElement(name = "service", type = ComponentService.class), @XmlElement(name = "reference", type = ComponentReference.class), @XmlElement(name = "property", type = PropertyValue.class) })
	protected List<Object> servicesAndReferencesAndProperties;
	@XmlAttribute(name = "name", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String name;

	/**
	 * Gets the value of the implementation property.
	 * 
	 * @return possible object is {@link JAXBElement }{@code <}
	 *         {@link Implementation }{@code >} {@link JAXBElement }{@code <}
	 *         {@link Instance }{@code >}
	 * 
	 */
	public JAXBElement<? extends Implementation> getImplementation() {
		return implementation;
	}

	/**
	 * Sets the value of the implementation property.
	 * 
	 * @param value
	 *            allowed object is {@link JAXBElement }{@code <}
	 *            {@link Implementation }{@code >} {@link JAXBElement }{@code <}
	 *            {@link Instance }{@code >}
	 * 
	 */
	public void setImplementation(JAXBElement<? extends Implementation> value) {
		this.implementation = value;
	}

	/**
	 * Gets the value of the servicesAndReferencesAndProperties property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the servicesAndReferencesAndProperties
	 * property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getServicesAndReferencesAndProperties().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ComponentService } {@link ComponentReference }
	 * {@link PropertyValue }
	 * 
	 * 
	 */
	public List<Object> getServicesAndReferencesAndProperties() {
		if (servicesAndReferencesAndProperties == null) {
			servicesAndReferencesAndProperties = new ArrayList<Object>();
		}
		return this.servicesAndReferencesAndProperties;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

}
